const menaJmenoEN = {
  "AED": "Arab Emirates Dirham",
  "AFN": "Afghan Afghani",
  "ALL": "Albanian Lek",
  "AMD": "Armenian Dram",
  "ANG": "Antillean Guilder",
  "AOA": "Angolan Kwanza",
  "ARS": "Argentine Peso",
  "AUD": "Australian Dollar",
  "AWG": "Aruban Florin",
  "AZN": "Azerbaijani Manat",
  "BAM": "Convertible Mark",
  "BBD": "Barbadian Dollar",
  "BDT": "Bangladeshi Taka",
  "BGN": "Bulgarian Lev",
  "BHD": "Bahraini Dinar",
  "BIF": "Burundian Franc",
  "BMD": "Bermudan Dollar",
  "BND": "Brunei Dollar",
  "BOB": "Bolivian Boliviano",
  "BRL": "Brazilian Real",
  "BSD": "Bahamian Dollar",
  "BTC": "Bitcoin",
  "BTN": "Bhutanese Ngultrum",
  "BWP": "Botswanan Pula",
  "BYN": "Belarusian Ruble",
  "BZD": "Belize Dollar",
  "CAD": "Canadian Dollar",
  "CDF": "Congolese Franc",
  "CHF": "Swiss Franc",
  "CLF": "Chilean Unit of Account",
  "CLP": "Chilean Peso",
  "CNH": "Chinese Yuan (Offshore)",
  "CNY": "Chinese Yuan",
  "COP": "Colombian Peso",
  "CRC": "Costa Rican Colón",
  "CUC": "Cuban Convertible Peso",
  "CUP": "Cuban Peso",
  "CVE": "Cape Verdean Escudo",
  "CZK": "Czech Republic Koruna",
  "DJF": "Djiboutian Franc",
  "DKK": "Danish Krone",
  "DOP": "Dominican Peso",
  "DZD": "Algerian Dinar",
  "EGP": "Egyptian Pound",
  "ERN": "Eritrean Nakfa",
  "ETB": "Ethiopian Birr",
  "EUR": "Euro",
  "FJD": "Fijian Dollar",
  "FKP": "Falkland Islands Pound",
  "GBP": "British Pound Sterling",
  "GEL": "Georgian Lari",
  "GGP": "Guernsey Pound",
  "GHS": "Ghanaian Cedi",
  "GIP": "Gibraltar Pound",
  "GMD": "Gambian Dalasi",
  "GNF": "Guinean Franc",
  "GTQ": "Guatemalan Quetzal",
  "GYD": "Guyanaese Dollar",
  "HKD": "Hong Kong Dollar",
  "HNL": "Honduran Lempira",
  "HRK": "Croatian Kuna",
  "HTG": "Haitian Gourde",
  "HUF": "Hungarian Forint",
  "IDR": "Indonesian Rupiah",
  "ILS": "Israeli New Sheqel",
  "IMP": "Manx pound",
  "INR": "Indian Rupee",
  "IQD": "Iraqi Dinar",
  "IRR": "Iranian Rial",
  "ISK": "Icelandic Króna",
  "JEP": "Jersey Pound",
  "JMD": "Jamaican Dollar",
  "JOD": "Jordanian Dinar",
  "JPY": "Japanese Yen",
  "KES": "Kenyan Shilling",
  "KGS": "Kyrgystani Som",
  "KHR": "Cambodian Riel",
  "KMF": "Comorian Franc",
  "KPW": "North Korean Won",
  "KRW": "South Korean Won",
  "KWD": "Kuwaiti Dinar",
  "KYD": "Cayman Islands Dollar",
  "KZT": "Kazakhstani Tenge",
  "LAK": "Laotian Kip",
  "LBP": "Lebanese Pound",
  "LKR": "Sri Lankan Rupee",
  "LRD": "Liberian Dollar",
  "LSL": "Lesotho Loti",
  "LYD": "Libyan Dinar",
  "MAD": "Moroccan Dirham",
  "MDL": "Moldovan Leu",
  "MGA": "Malagasy Ariary",
  "MKD": "Macedonian Denar",
  "MMK": "Myanma Kyat",
  "MNT": "Mongolian Tugrik",
  "MOP": "Macanese Pataca",
  "MRU": "Mauritanian Ouguiya",
  "MUR": "Mauritian Rupee",
  "MVR": "Maldivian Rufiyaa",
  "MWK": "Malawian Kwacha",
  "MXN": "Mexican Peso",
  "MYR": "Malaysian Ringgit",
  "MZN": "Mozambican Metical",
  "NAD": "Namibian Dollar",
  "NGN": "Nigerian Naira",
  "NIO": "Nicaraguan Córdoba",
  "NOK": "Norwegian Krone",
  "NPR": "Nepalese Rupee",
  "NZD": "New Zealand Dollar",
  "OMR": "Omani Rial",
  "PAB": "Panamanian Balboa",
  "PEN": "Peruvian Nuevo Sol",
  "PGK": "Papua New Guinean Kina",
  "PHP": "Philippine Peso",
  "PKR": "Pakistani Rupee",
  "PLN": "Polish Zloty",
  "PYG": "Paraguayan Guarani",
  "QAR": "Qatari Rial",
  "RON": "Romanian Leu",
  "RSD": "Serbian Dinar",
  "RUB": "Russian Ruble",
  "RWF": "Rwandan Franc",
  "SAR": "Saudi Riyal",
  "SBD": "Solomon Islands Dollar",
  "SCR": "Seychellois Rupee",
  "SDG": "Sudanese Pound",
  "SEK": "Swedish Krona",
  "SGD": "Singapore Dollar",
  "SHP": "Saint Helena Pound",
  "SLL": "Sierra Leonean Leone",
  "SOS": "Somali Shilling",
  "SRD": "Surinamese Dollar",
  "SSP": "South Sudanese Pound",
  "STD": "Dobra (pre-2018)",
  "STN": "Dobra",
  "SVC": "Salvadoran Colón",
  "SYP": "Syrian Pound",
  "SZL": "Swazi Lilangeni",
  "THB": "Thai Baht",
  "TJS": "Tajikistani Somoni",
  "TMT": "Turkmenistani Manat",
  "TND": "Tunisian Dinar",
  "TOP": "Tongan Pa'anga",
  "TRY": "Turkish Lira",
  "TTD": "Trinidad and Tobago Dollar",
  "TWD": "New Taiwan Dollar",
  "TZS": "Tanzanian Shilling",
  "UAH": "Ukrainian Hryvnia",
  "UGX": "Ugandan Shilling",
  "USD": "United States Dollar",
  "UYU": "Uruguayan Peso",
  "UZS": "Uzbekistan Som",
  "VEF": "Venezuelan Bolívar Fuerte (Old)",
  "VES": "Venezuelan Bolívar Soberano",
  "VND": "Vietnamese Dong",
  "VUV": "Vanuatu Vatu",
  "WST": "Samoan Tala",
  "XAF": "CFA Franc BEAC",
  "XAG": "Silver Ounce",
  "XAU": "Gold Ounce",
  "XCD": "East Caribbean Dollar",
  "XDR": "Special Drawing Rights",
  "XOF": "CFA Franc BCEAO",
  "XPD": "Palladium Ounce",
  "XPF": "CFP Franc",
  "XPT": "Platinum Ounce",
  "YER": "Yemeni Rial",
  "ZAR": "South African Rand",
  "ZMW": "Zambian Kwacha",
  "ZWL": "Zimbabwean Dollar"
}
const menaJmenoCZ = {
  "AED": "Dirham arabských emirátů",
  "AFN": "Afghánský afghán",
  "ALL": "Albánský lek",
  "AMD": "Arménský dram",
  "ANG": "Nizozemskoantilský gulden",
  "AOA": "Angolská kwanza",
  "ARS": "Argentinské peso",
  "AUD": "Australský dolar",
  "AWG": "Arubský florin",
  "AZN": "Ázerbájdžánský manat",
  "BAM": "Konvertibilní marka",
  "BBD": "Barbadoský dolar",
  "BDT": "Bangladéšská taka",
  "BGN": "Bulharský lev",
  "BHD": "Bahrajnský dinár",
  "BIF": "Burundský frank",
  "BMD": "Bermudský dolar",
  "BND": "Brunejský dolar",
  "BOB": "Bolivijský boliviano",
  "BRL": "Brazilský real",
  "BSD": "Bahamský dolar",
  "BTC": "Bitcoin",
  "BTN": "Bhútánský ngultrum",
  "BWP": "Botswanská pula",
  "BYN": "Běloruský rubl",
  "BZD": "Belizský dolar",
  "CAD": "Kanadský dolar",
  "CDF": "Konžský frank",
  "CHF": "Švýcarský frank",
  "CLF": "Chilská účetní jednotka (UF)",
  "CLP": "Chilské peso",
  "CNH": "Čínský jüan (offshore)",
  "CNY": "Čínský jüan",
  "COP": "Kolumbijské peso",
  "CRC": "Kostarický colón",
  "CUC": "Kubánské konvertibilní peso",
  "CUP": "Kubánské peso",
  "CVE": "Kapverdský escudo",
  "CZK": "Česká koruna",
  "DJF": "Džibutský frank",
  "DKK": "Dánská koruna",
  "DOP": "Dominikánské peso",
  "DZD": "Alžírský dinár",
  "EGP": "Egyptská libra",
  "ERN": "Eritrejská nakfa",
  "ETB": "Etiopský birr",
  "EUR": "Euro",
  "FJD": "Fidžijský dolar",
  "FKP": "Falklandská libra",
  "GBP": "Britská libra šterlinků",
  "GEL": "Gruzínský lari",
  "GGP": "Guernseyská libra",
  "GHS": "Ghanský cedi",
  "GIP": "Gibraltarská libra",
  "GMD": "Gambijský dalasi",
  "GNF": "Guinejský frank",
  "GTQ": "Guatemalský quetzal",
  "GYD": "Guyanský dolar",
  "HKD": "Hongkongský dolar",
  "HNL": "Honduraská lempira",
  "HRK": "Chorvatská kuna",
  "HTG": "Haitský gourde",
  "HUF": "Maďarský forint",
  "IDR": "Indonéská rupie",
  "ILS": "Izraelský nový šekel",
  "IMP": "Manská libra",
  "INR": "Indická rupie",
  "IQD": "Irácký dinár",
  "IRR": "Íránský rijál",
  "ISK": "Islandská koruna",
  "JEP": "Jersey libra",
  "JMD": "Jamajský dolar",
  "JOD": "Jordánský dinár",
  "JPY": "Japonský jen",
  "KES": "Keňský šilink",
  "KGS": "Kyrgyzský som",
  "KHR": "Kambodžský riel",
  "KMF": "Komorský frank",
  "KPW": "Severokorejský won",
  "KRW": "Jihokorejský won",
  "KWD": "Kuvajtský dinár",
  "KYD": "Kajmanský dolar",
  "KZT": "Kazachstánský tenge",
  "LAK": "Laoský kip",
  "LBP": "Libanonská libra",
  "LKR": "Srílanská rupie",
  "LRD": "Liberský dolar",
  "LSL": "Lesothský loti",
  "LYD": "Libyjský dinár",
  "MAD": "Marocký dirham",
  "MDL": "Moldavský leu",
  "MGA": "Madagaskarský ariary",
  "MKD": "Makedonský denár",
  "MMK": "Myanmarský kyat",
  "MNT": "Mongolský tugrik",
  "MOP": "Macao pataca",
  "MRU": "Mauretánská ouguiya",
  "MUR": "Mauricijská rupie",
  "MVR": "Maledivská rufiyaa",
  "MWK": "Malawijská kwacha",
  "MXN": "Mexické peso",
  "MYR": "Malajsijský ringgit",
  "MZN": "Mosambický metical",
  "NAD": "Namibijský dolar",
  "NGN": "Nigerijská naira",
  "NIO": "Nikaragujská córdoba",
  "NOK": "Norská koruna",
  "NPR": "Nepálská rupie",
  "NZD": "Novozélandský dolar",
  "OMR": "Ománský rijál",
  "PAB": "Panamská balboa",
  "PEN": "Peruánský nuevo sol",
  "PGK": "Papua-novoguinejská kina",
  "PHP": "Filipínské peso",
  "PKR": "Pákistánská rupie",
  "PLN": "Polský zlotý",
  "PYG": "Paraguayský guarani",
  "QAR": "Katarský rijál",
  "RON": "Rumunský leu",
  "RSD": "Srbský dinár",
  "RUB": "Ruský rubl",
  "RWF": "Rwandský frank",
  "SAR": "Saúdský rijál",
  "SBD": "Šalamounský dolar",
  "SCR": "Seychelská rupie",
  "SDG": "Súdánská libra",
  "SEK": "Švédská koruna",
  "SGD": "Singapurský dolar",
  "SHP": "Svatá Helena libra",
  "SLL": "Sierraleonský leone",
  "SOS": "Somálský šilink",
  "SRD": "Surinamský dolar",
  "SSP": "Jiho súdánská libra",
  "STD": "Dobra(před 2018)",
  "STN": "Dobra",
  "SVC": "Salvadorský colón",
  "SYP": "Syrská libra",
  "SZL": "Svazijský lilangeni",
  "THB": "Thajský baht",
  "TJS": "Tádžikistánský somoni",
  "TMT": "Turkmenistánský manat",
  "TND": "Tuniský dinár",
  "TOP": "Tonžská paʻanga",
  "TRY": "Turecká lira",
  "TTD": "Trinidadský dolar",
  "TWD": "Nový tchajwanský dolar",
  "TZS": "Tanzanský šilink",
  "UAH": "Ukrajinská hřivna",
  "UGX": "Ugandský šilink",
  "USD": "Americký dolar",
  "UYU": "Uruguayské peso",
  "UZS": "Uzbecký som",
  "VEF": "Venezuelský bolívar(starý)",
  "VES": "Venezuelský bolívar",
  "VND": "Vietnamský dong",
  "VUV": "Vanuatský vatu",
  "WST": "Samojská tala",
  "XAF": "CFA frank BEAC",
  "XAG": "Stříbrná unce",
  "XAU": "Zlatá unce",
  "XCD": "Východokaribský dolar",
  "XDR": "Zvláštní práva čerpání",
  "XOF": "CFA frank BCEAO",
  "XPD": "Palladiová unce",
  "XPF": "CFP frank",
  "XPT": "Platinová unce",
  "YER": "Jemenský rijál",
  "ZAR": "Jihoafrický rand",
  "ZMW": "Zambijská kwacha",
  "ZWL": "Zimbabwský dolar"
}
const menaStatEN = {
  "AED": "United Arab Emirates",
  "AFN": "Afghanistan",
  "ALL": "Albania",
  "AMD": "Armenia",
  "ANG": "Netherlands Antilles",
  "AOA": "Angola",
  "ARS": "Argentina",
  "AUD": "Australia",
  "AWG": "Aruba",
  "AZN": "Azerbaijan",
  "BAM": "Bosnia and Herzegovina",
  "BBD": "Barbados",
  "BDT": "Bangladesh",
  "BGN": "Bulgaria",
  "BHD": "Bahrain",
  "BIF": "Burundi",
  "BMD": "Bermuda",
  "BND": "Brunei",
  "BOB": "Bolivia",
  "BRL": "Brazil",
  "BSD": "Bahamas",
  "BTC": "Cryptocurrency",
  "BTN": "Bhutan",
  "BWP": "Botswana",
  "BYN": "Belarus",
  "BZD": "Belize",
  "CAD": "Canada",
  "CDF": "Democratic Republic of the Congo",
  "CHF": "Switzerland",
  "CLF": "Chile",
  "CLP": "Chile",
  "CNH": "China (Offshore)",
  "CNY": "China",
  "COP": "Colombia",
  "CRC": "Costa Rica",
  "CUC": "Cuba",
  "CUP": "Cuba",
  "CVE": "Cape Verde",
  "CZK": "Czech Republic",
  "DJF": "Djibouti",
  "DKK": "Denmark",
  "DOP": "Dominican Republic",
  "DZD": "Algeria",
  "EGP": "Egypt",
  "ERN": "Eritrea",
  "ETB": "Ethiopia",
  "EUR": "Eurozone",
  "FJD": "Fiji",
  "FKP": "Falkland Islands",
  "GBP": "United Kingdom",
  "GEL": "Georgia",
  "GGP": "Guernsey",
  "GHS": "Ghana",
  "GIP": "Gibraltar",
  "GMD": "Gambia",
  "GNF": "Guinea",
  "GTQ": "Guatemala",
  "GYD": "Guyana",
  "HKD": "Hong Kong",
  "HNL": "Honduras",
  "HRK": "Croatia",
  "HTG": "Haiti",
  "HUF": "Hungary",
  "IDR": "Indonesia",
  "ILS": "Israel",
  "IMP": "Isle of Man",
  "INR": "India",
  "IQD": "Iraq",
  "IRR": "Iran",
  "ISK": "Iceland",
  "JEP": "Jersey",
  "JMD": "Jamaica",
  "JOD": "Jordan",
  "JPY": "Japan",
  "KES": "Kenya",
  "KGS": "Kyrgyzstan",
  "KHR": "Cambodia",
  "KMF": "Comoros",
  "KPW": "North Korea",
  "KRW": "South Korea",
  "KWD": "Kuwait",
  "KYD": "Cayman Islands",
  "KZT": "Kazakhstan",
  "LAK": "Laos",
  "LBP": "Lebanon",
  "LKR": "Sri Lanka",
  "LRD": "Liberia",
  "LSL": "Lesotho",
  "LYD": "Libya",
  "MAD": "Morocco",
  "MDL": "Moldova",
  "MGA": "Madagascar",
  "MKD": "North Macedonia",
  "MMK": "Myanmar",
  "MNT": "Mongolia",
  "MOP": "Macau",
  "MRU": "Mauritania",
  "MUR": "Mauritius",
  "MVR": "Maldives",
  "MWK": "Malawi",
  "MXN": "Mexico",
  "MYR": "Malaysia",
  "MZN": "Mozambique",
  "NAD": "Namibia",
  "NGN": "Nigeria",
  "NIO": "Nicaragua",
  "NOK": "Norway",
  "NPR": "Nepal",
  "NZD": "New Zealand",
  "OMR": "Oman",
  "PAB": "Panama",
  "PEN": "Peru",
  "PGK": "Papua New Guinea",
  "PHP": "Philippines",
  "PKR": "Pakistan",
  "PLN": "Poland",
  "PYG": "Paraguay",
  "QAR": "Qatar",
  "RON": "Romania",
  "RSD": "Serbia",
  "RUB": "Russia",
  "RWF": "Rwanda",
  "SAR": "Saudi Arabia",
  "SBD": "Solomon Islands",
  "SCR": "Seychelles",
  "SDG": "Sudan",
  "SEK": "Sweden",
  "SGD": "Singapore",
  "SHP": "Saint Helena",
  "SLL": "Sierra Leone",
  "SOS": "Somalia",
  "SRD": "Suriname",
  "SSP": "South Sudan",
  "STD": "São Tomé and Príncipe (pre-2018)",
  "STN": "São Tomé and Príncipe",
  "SVC": "El Salvador",
  "SYP": "Syria",
  "SZL": "Eswatini",
  "THB": "Thailand",
  "TJS": "Tajikistan",
  "TMT": "Turkmenistan",
  "TND": "Tunisia",
  "TOP": "Tonga",
  "TRY": "Turkey",
  "TTD": "Trinidad and Tobago",
  "TWD": "Taiwan",
  "TZS": "Tanzania",
  "UAH": "Ukraine",
  "UGX": "Uganda",
  "USD": "United States",
  "UYU": "Uruguay",
  "UZS": "Uzbekistan",
  "VEF": "Venezuela (Old)",
  "VES": "Venezuela",
  "VND": "Vietnam",
  "VUV": "Vanuatu",
  "WST": "Samoa",
  "XAF": "CEMAC countries",
  "XAG": "International",
  "XAU": "International",
  "XCD": "East Caribbean states",
  "XDR": "International Monetary Fund",
  "XOF": "WAEMU countries",
  "XPD": "International",
  "XPF": "French territories in the Pacific",
  "XPT": "International",
  "YER": "Yemen",
  "ZAR": "South Africa",
  "ZMW": "Zambia",
  "ZWL": "Zimbabwe"
}
const menaStatCZ = {
  "AED": "Spojené arabské emiráty",
  "AFN": "Afghánistán",
  "ALL": "Albánie",
  "AMD": "Arménie",
  "ANG": "Nizozemské Antily",
  "AOA": "Angola",
  "ARS": "Argentina",
  "AUD": "Austrálie",
  "AWG": "Aruba",
  "AZN": "Ázerbájdžán",
  "BAM": "Bosna a Hercegovina",
  "BBD": "Barbados",
  "BDT": "Bangladéš",
  "BGN": "Bulharsko",
  "BHD": "Bahrajn",
  "BIF": "Burundi",
  "BMD": "Bermudy",
  "BND": "Brunej",
  "BOB": "Bolívie",
  "BRL": "Brazílie",
  "BSD": "Bahamy",
  "BTC": "Kryptoměna",
  "BTN": "Bhútán",
  "BWP": "Botswana",
  "BYN": "Bělorusko",
  "BZD": "Belize",
  "CAD": "Kanada",
  "CDF": "Demokratická republika Kongo",
  "CHF": "Švýcarsko",
  "CLF": "Chile",
  "CLP": "Chile",
  "CNH": "Čína (offshore)",
  "CNY": "Čína",
  "COP": "Kolumbie",
  "CRC": "Kostarika",
  "CUC": "Kuba",
  "CUP": "Kuba",
  "CVE": "Kapverdy",
  "CZK": "Česká republika",
  "DJF": "Džibutsko",
  "DKK": "Dánsko",
  "DOP": "Dominikánská republika",
  "DZD": "Alžírsko",
  "EGP": "Egypt",
  "ERN": "Eritrea",
  "ETB": "Etiopie",
  "EUR": "Eurozóna",
  "FJD": "Fidži",
  "FKP": "Falklandy",
  "GBP": "Spojené království",
  "GEL": "Gruzie",
  "GGP": "Guernsey",
  "GHS": "Ghana",
  "GIP": "Gibraltar",
  "GMD": "Gambie",
  "GNF": "Guinea",
  "GTQ": "Guatemala",
  "GYD": "Guyana",
  "HKD": "Hongkong",
  "HNL": "Honduras",
  "HRK": "Chorvatsko",
  "HTG": "Haiti",
  "HUF": "Maďarsko",
  "IDR": "Indonésie",
  "ILS": "Izrael",
  "IMP": "Ostrov Man",
  "INR": "Indie",
  "IQD": "Irák",
  "IRR": "Írán",
  "ISK": "Island",
  "JEP": "Jersey",
  "JMD": "Jamajka",
  "JOD": "Jordánsko",
  "JPY": "Japonsko",
  "KES": "Keňa",
  "KGS": "Kyrgyzstán",
  "KHR": "Kambodža",
  "KMF": "Komory",
  "KPW": "Severní Korea",
  "KRW": "Jižní Korea",
  "KWD": "Kuvajt",
  "KYD": "Kajmanské ostrovy",
  "KZT": "Kazachstán",
  "LAK": "Laos",
  "LBP": "Libanon",
  "LKR": "Srí Lanka",
  "LRD": "Libérie",
  "LSL": "Lesotho",
  "LYD": "Libye",
  "MAD": "Maroko",
  "MDL": "Moldavsko",
  "MGA": "Madagaskar",
  "MKD": "Severní Makedonie",
  "MMK": "Myanmar",
  "MNT": "Mongolsko",
  "MOP": "Macao",
  "MRU": "Mauritánie",
  "MUR": "Mauricius",
  "MVR": "Maledivy",
  "MWK": "Malawi",
  "MXN": "Mexiko",
  "MYR": "Malajsie",
  "MZN": "Mosambik",
  "NAD": "Namibie",
  "NGN": "Nigérie",
  "NIO": "Nikaragua",
  "NOK": "Norsko",
  "NPR": "Nepál",
  "NZD": "Nový Zéland",
  "OMR": "Omán",
  "PAB": "Panama",
  "PEN": "Peru",
  "PGK": "Papua-Nová Guinea",
  "PHP": "Filipíny",
  "PKR": "Pákistán",
  "PLN": "Polsko",
  "PYG": "Paraguay",
  "QAR": "Katar",
  "RON": "Rumunsko",
  "RSD": "Srbsko",
  "RUB": "Rusko",
  "RWF": "Rwanda",
  "SAR": "Saúdská Arábie",
  "SBD": "Šalamounovy ostrovy",
  "SCR": "Seychely",
  "SDG": "Súdán",
  "SEK": "Švédsko",
  "SGD": "Singapur",
  "SHP": "Svatá Helena",
  "SLL": "Sierra Leone",
  "SOS": "Somálsko",
  "SRD": "Surinam",
  "SSP": "Jižní Súdán",
  "STD": "Svatý Tomáš a Princův ostrov (před 2018)",
  "STN": "Svatý Tomáš a Princův ostrov",
  "SVC": "Salvador",
  "SYP": "Sýrie",
  "SZL": "Eswatini",
  "THB": "Thajsko",
  "TJS": "Tádžikistán",
  "TMT": "Turkmenistán",
  "TND": "Tunisko",
  "TOP": "Tonga",
  "TRY": "Turecko",
  "TTD": "Trinidad a Tobago",
  "TWD": "Tchaj-wan",
  "TZS": "Tanzanie",
  "UAH": "Ukrajina",
  "UGX": "Uganda",
  "USD": "Spojené státy",
  "UYU": "Uruguay",
  "UZS": "Uzbekistán",
  "VEF": "Venezuela (starý)",
  "VES": "Venezuela",
  "VND": "Vietnam",
  "VUV": "Vanuatu",
  "WST": "Samoa",
  "XAF": "Země CEMAC ",
  "XAG": "Mezinárodní",
  "XAU": "Mezinárodní",
  "XCD": "Středoamerické státy",
  "XDR": "Mezinárodní měnový fond",
  "XOF": "Země WAEMU",
  "XPD": "Mezinárodní",
  "XPF": "Francouzské území v Pacifiku",
  "XPT": "Mezinárodní",
  "YER": "Jemen",
  "ZAR": "Jihoafrická republika",
  "ZMW": "Zambie",
  "ZWL": "Zimbabwe"
}
const menaVlajky = {
  "AED": "ae",
  "AFN": "af",
  "ALL": "al",
  "AMD": "am",
  "ANG": "cw",
  "AOA": "ao",
  "ARS": "ar",
  "AUD": "au",
  "AWG": "aw",
  "AZN": "az",
  "BAM": "ba",
  "BBD": "bb",
  "BDT": "bd",
  "BGN": "bg",
  "BHD": "bh",
  "BIF": "bi",
  "BMD": "bm",
  "BND": "bn",
  "BOB": "bo",
  "BRL": "br",
  "BSD": "bs",
  "BTC": "xx",
  "BTN": "bt",
  "BWP": "bw",
  "BYN": "by",
  "BZD": "bz",
  "CAD": "ca",
  "CDF": "cd",
  "CHF": "ch",
  "CLF": "cl",
  "CLP": "cl",
  "CNH": "cn",
  "CNY": "cn",
  "COP": "co",
  "CRC": "cr",
  "CUC": "cu",
  "CUP": "cu",
  "CVE": "cv",
  "CZK": "cz",
  "DJF": "dj",
  "DKK": "dk",
  "DOP": "do",
  "DZD": "dz",
  "EGP": "eg",
  "ERN": "er",
  "ETB": "et",
  "EUR": "eu",
  "FJD": "fj",
  "FKP": "fk",
  "GBP": "gb",
  "GEL": "ge",
  "GGP": "gg",
  "GHS": "gh",
  "GIP": "gi",
  "GMD": "gm",
  "GNF": "gn",
  "GTQ": "gt",
  "GYD": "gy",
  "HKD": "hk",
  "HNL": "hn",
  "HRK": "hr",
  "HTG": "ht",
  "HUF": "hu",
  "IDR": "id",
  "ILS": "il",
  "IMP": "im",
  "INR": "in",
  "IQD": "iq",
  "IRR": "ir",
  "ISK": "is",
  "JEP": "je",
  "JMD": "jm",
  "JOD": "jo",
  "JPY": "jp",
  "KES": "ke",
  "KGS": "kg",
  "KHR": "kh",
  "KMF": "km",
  "KPW": "kp",
  "KRW": "kr",
  "KWD": "kw",
  "KYD": "ky",
  "KZT": "kz",
  "LAK": "la",
  "LBP": "lb",
  "LKR": "lk",
  "LRD": "lr",
  "LSL": "ls",
  "LYD": "ly",
  "MAD": "ma",
  "MDL": "md",
  "MGA": "mg",
  "MKD": "mk",
  "MMK": "mm",
  "MNT": "mn",
  "MOP": "mo",
  "MRU": "mr",
  "MUR": "mu",
  "MVR": "mv",
  "MWK": "mw",
  "MXN": "mx",
  "MYR": "my",
  "MZN": "mz",
  "NAD": "na",
  "NGN": "ng",
  "NIO": "ni",
  "NOK": "no",
  "NPR": "np",
  "NZD": "nz",
  "OMR": "om",
  "PAB": "pa",
  "PEN": "pe",
  "PGK": "pg",
  "PHP": "ph",
  "PKR": "pk",
  "PLN": "pl",
  "PYG": "py",
  "QAR": "qa",
  "RON": "ro",
  "RSD": "rs",
  "RUB": "ru",
  "RWF": "rw",
  "SAR": "sa",
  "SBD": "sb",
  "SCR": "sc",
  "SDG": "sd",
  "SEK": "se",
  "SGD": "sg",
  "SHP": "sh",
  "SLL": "sl",
  "SOS": "so",
  "SRD": "sr",
  "SSP": "ss",
  "STD": "st",
  "STN": "st",
  "SVC": "sv",
  "SYP": "sy",
  "SZL": "sz",
  "THB": "th",
  "TJS": "tj",
  "TMT": "tm",
  "TND": "tn",
  "TOP": "to",
  "TRY": "tr",
  "TTD": "tt",
  "TWD": "tw",
  "TZS": "tz",
  "UAH": "ua",
  "UGX": "ug",
  "USD": "us",
  "UYU": "uy",
  "UZS": "uz",
  "VEF": "ve",
  "VES": "ve",
  "VND": "vn",
  "VUV": "vu",
  "WST": "ws",
  "XAF": "cm",
  "XAG": "xx",
  "XAU": "xx",
  "XCD": "ag",
  "XDR": "xx",
  "XOF": "sn",
  "XPD": "xx",
  "XPF": "pf",
  "XPT": "xx",
  "YER": "ye",
  "ZAR": "za",
  "ZMW": "zm",
  "ZWL": "zw"
};
//Seznam, který se zdá na první pohled zbytečný a nesmyslný, ale zatím přes něj mám udělaný kontrolovač url parametrů, který v případě že v tomto seznamu měnu nenajde, tak zaklMena nastaví na CZK
//Možné zlepšení: Obejít se bez tohoto seznamu, takže by byl kratší kód
const menyseznam = {
  "AED": "AED",
  "AFN": "AFN",
  "ALL": "ALL",
  "AMD": "AMD",
  "ANG": "ANG",
  "AOA": "AOA",
  "ARS": "ARS",
  "AUD": "AUD",
  "AWG": "AWG",
  "AZN": "AZN",
  "BAM": "BAM",
  "BBD": "BBD",
  "BDT": "BDT",
  "BGN": "BGN",
  "BHD": "BHD",
  "BIF": "BIF",
  "BMD": "BMD",
  "BND": "BND",
  "BOB": "BOB",
  "BRL": "BRL",
  "BSD": "BSD",
  "BTC": "BTC",
  "BTN": "BTN",
  "BWP": "BWP",
  "BYN": "BYN",
  "BZD": "BZD",
  "CAD": "CAD",
  "CDF": "CDF",
  "CHF": "CHF",
  "CLF": "CLF",
  "CLP": "CLP",
  "CNH": "CNH",
  "CNY": "CNY",
  "COP": "COP",
  "CRC": "CRC",
  "CUC": "CUC",
  "CUP": "CUP",
  "CVE": "CVE",
  "CZK": "CZK",
  "DJF": "DJF",
  "DKK": "DKK",
  "DOP": "DOP",
  "DZD": "DZD",
  "EGP": "EGP",
  "ERN": "ERN",
  "ETB": "ETB",
  "EUR": "EUR",
  "FJD": "FJD",
  "FKP": "FKP",
  "GBP": "GBP",
  "GEL": "GEL",
  "GGP": "GGP",
  "GHS": "GHS",
  "GIP": "GIP",
  "GMD": "GMD",
  "GNF": "GNF",
  "GTQ": "GTQ",
  "GYD": "GYD",
  "HKD": "HKD",
  "HNL": "HNL",
  "HRK": "HRK",
  "HTG": "HTG",
  "HUF": "HUF",
  "IDR": "IDR",
  "ILS": "ILS",
  "IMP": "IMP",
  "INR": "INR",
  "IQD": "IQD",
  "IRR": "IRR",
  "ISK": "ISK",
  "JEP": "JEP",
  "JMD": "JMD",
  "JOD": "JOD",
  "JPY": "JPY",
  "KES": "KES",
  "KGS": "KGS",
  "KHR": "KHR",
  "KMF": "KMF",
  "KPW": "KPW",
  "KRW": "KRW",
  "KWD": "KWD",
  "KYD": "KYD",
  "KZT": "KZT",
  "LAK": "LAK",
  "LBP": "LBP",
  "LKR": "LKR",
  "LRD": "LRD",
  "LSL": "LSL",
  "LYD": "LYD",
  "MAD": "MAD",
  "MDL": "MDL",
  "MGA": "MGA",
  "MKD": "MKD",
  "MMK": "MMK",
  "MNT": "MNT",
  "MOP": "MOP",
  "MRU": "MRU",
  "MUR": "MUR",
  "MVR": "MVR",
  "MWK": "MWK",
  "MXN": "MXN",
  "MYR": "MYR",
  "MZN": "MZN",
  "NAD": "NAD",
  "NGN": "NGN",
  "NIO": "NIO",
  "NOK": "NOK",
  "NPR": "NPR",
  "NZD": "NZD",
  "OMR": "OMR",
  "PAB": "PAB",
  "PEN": "PEN",
  "PGK": "PGK",
  "PHP": "PHP",
  "PKR": "PKR",
  "PLN": "PLN",
  "PYG": "PYG",
  "QAR": "QAR",
  "RON": "RON",
  "RSD": "RSD",
  "RUB": "RUB",
  "RWF": "RWF",
  "SAR": "SAR",
  "SBD": "SBD",
  "SCR": "SCR",
  "SDG": "SDG",
  "SEK": "SEK",
  "SGD": "SGD",
  "SHP": "SHP",
  "SLL": "SLL",
  "SOS": "SOS",
  "SRD": "SRD",
  "SSP": "SSP",
  "STD": "STD",
  "STN": "STN",
  "SVC": "SVC",
  "SYP": "SYP",
  "SZL": "SZL",
  "THB": "THB",
  "TJS": "TJS",
  "TMT": "TMT",
  "TND": "TND",
  "TOP": "TOP",
  "TRY": "TRY",
  "TTD": "TTD",
  "TWD": "TWD",
  "TZS": "TZS",
  "UAH": "UAH",
  "UGX": "UGX",
  "USD": "USD",
  "UYU": "UYU",
  "UZS": "UZS",
  "VEF": "VEF",
  "VES": "VES",
  "VND": "VND",
  "VUV": "VUV",
  "WST": "WST",
  "XAF": "XAF",
  "XAG": "XAG",
  "XAU": "XAU",
  "XCD": "XCD",
  "XDR": "XDR",
  "XOF": "XOF",
  "XPD": "XPD",
  "XPF": "XPF",
  "XPT": "XPT",
  "YER": "YER",
  "ZAR": "ZAR",
  "ZMW": "ZMW",
  "ZWL": "ZWL"
}
//U jednotlivých kódů zemí je zde přiřazen znak měny
var menaVs = {
  "AED": "د.إ",
  "AFN": "؋",
  "ALL": "L",
  "AMD": "֏",
  "ANG": "ƒ",
  "AOA": "Kz",
  "ARS": "$",
  "AUD": "$",
  "AWG": "ƒ",
  "AZN": "₼",
  "BAM": "KM",
  "BBD": "$",
  "BDT": "৳",
  "BGN": "лв",
  "BHD": ".د.ب",
  "BIF": "FBu",
  "BMD": "$",
  "BND": "$",
  "BOB": "Bs.",
  "BRL": "R$",
  "BSD": "$",
  "BTC": "₿",
  "BTN": "Nu.",
  "BWP": "P",
  "BYN": "Br",
  "BZD": "$",
  "CAD": "$",
  "CDF": "FC",
  "CHF": "Fr.",
  "CLF": "UF",
  "CLP": "$",
  "CNH": "¥",
  "CNY": "¥",
  "COP": "$",
  "CRC": "₡",
  "CUC": "$",
  "CUP": "$",
  "CVE": "$",
  "CZK": "Kč",
  "DJF": "Fdj",
  "DKK": "kr",
  "DOP": "$",
  "DZD": "دج",
  "EGP": "£",
  "ERN": "Nfk",
  "ETB": "Br",
  "EUR": "€",
  "FJD": "$",
  "FKP": "£",
  "GBP": "£",
  "GEL": "₾",
  "GGP": "£",
  "GHS": "₵",
  "GIP": "£",
  "GMD": "D",
  "GNF": "FG",
  "GTQ": "Q",
  "GYD": "$",
  "HKD": "$",
  "HNL": "L",
  "HRK": "kn",
  "HTG": "G",
  "HUF": "Ft",
  "IDR": "Rp",
  "ILS": "₪",
  "IMP": "£",
  "INR": "₹",
  "IQD": "ع.د",
  "IRR": "﷼",
  "ISK": "kr",
  "JEP": "£",
  "JMD": "$",
  "JOD": "د.ا",
  "JPY": "¥",
  "KES": "Sh",
  "KGS": "сом",
  "KHR": "៛",
  "KMF": "CF",
  "KPW": "₩",
  "KRW": "₩",
  "KWD": "د.ك",
  "KYD": "$",
  "KZT": "₸",
  "LAK": "₭",
  "LBP": "ل.ل",
  "LKR": "Rs",
  "LRD": "$",
  "LSL": "L",
  "LYD": "ل.د",
  "MAD": "د.م.",
  "MDL": "L",
  "MGA": "Ar",
  "MKD": "ден",
  "MMK": "Ks",
  "MNT": "₮",
  "MOP": "P",
  "MRU": "UM",
  "MUR": "₨",
  "MVR": "Rf",
  "MWK": "MK",
  "MXN": "$",
  "MYR": "RM",
  "MZN": "MT",
  "NAD": "$",
  "NGN": "₦",
  "NIO": "C$",
  "NOK": "kr",
  "NPR": "₨",
  "NZD": "$",
  "OMR": "ر.ع.",
  "PAB": "B/.",
  "PEN": "S/",
  "PGK": "K",
  "PHP": "₱",
  "PKR": "₨",
  "PLN": "zł",
  "PYG": "₲",
  "QAR": "ر.ق",
  "RON": "lei",
  "RSD": "дин.",
  "RUB": "₽",
  "RWF": "FRw",
  "SAR": "ر.س",
  "SBD": "$",
  "SCR": "₨",
  "SDG": "ج.س.",
  "SEK": "kr",
  "SGD": "$",
  "SHP": "£",
  "SLL": "Le",
  "SOS": "Sh",
  "SRD": "$",
  "SSP": "£",
  "STD": "Db",
  "STN": "Db",
  "SVC": "₡",
  "SYP": "£",
  "SZL": "L",
  "THB": "฿",
  "TJS": "ЅМ",
  "TMT": "m",
  "TND": "د.ت",
  "TOP": "T$",
  "TRY": "₺",
  "TTD": "$",
  "TWD": "NT$",
  "TZS": "Sh",
  "UAH": "₴",
  "UGX": "Sh",
  "USD": "$",
  "UYU": "$",
  "UZS": "сўм",
  "VEF": "Bs",
  "VES": "Bs",
  "VND": "₫",
  "VUV": "Vt",
  "WST": "T",
  "XAF": "FCFA",
  "XAG": "Ag",
  "XAU": "Au",
  "XCD": "$",
  "XDR": "SDR",
  "XOF": "CFA",
  "XPD": "Pd",
  "XPF": "₣",
  "XPT": "Pt",
  "YER": "﷼",
  "ZAR": "R",
  "ZMW": "ZK",
  "ZWL": "$"
}
let CodesBackup = [
  "AED", "AFN", "ALL", "AMD", "ANG", "AOA", "ARS", "AUD", "AWG", "AZN", "BAM", "BBD", "BDT", "BGN",
  "BHD", "BIF", "BMD", "BND", "BOB", "BRL", "BSD", "BTC", "BTN", "BWP", "BYN", "BZD", "CAD", "CDF",
  "CHF", "CLF", "CLP", "CNH", "CNY", "COP", "CRC", "CUC", "CUP", "CVE", "CZK", "DJF", "DKK", "DOP",
  "DZD", "EGP", "ERN", "ETB", "EUR", "FJD", "FKP", "GBP", "GEL", "GGP", "GHS", "GIP", "GMD", "GNF",
  "GTQ", "GYD", "HKD", "HNL", "HRK", "HTG", "HUF", "IDR", "ILS", "IMP", "INR", "IQD", "IRR", "ISK",
  "JEP", "JMD", "JOD", "JPY", "KES", "KGS", "KHR", "KMF", "KPW", "KRW", "KWD", "KYD", "KZT", "LAK",
  "LBP", "LKR", "LRD", "LSL", "LYD", "MAD", "MDL", "MGA", "MKD", "MMK", "MNT", "MOP", "MRU", "MUR",
  "MVR", "MWK", "MXN", "MYR", "MZN", "NAD", "NGN", "NIO", "NOK", "NPR", "NZD", "OMR", "PAB", "PEN",
  "PGK", "PHP", "PKR", "PLN", "PYG", "QAR", "RON", "RSD", "RUB", "RWF", "SAR", "SBD", "SCR", "SDG",
  "SEK", "SGD", "SHP", "SLL", "SOS", "SRD", "SSP", "STD", "STN", "SVC", "SYP", "SZL", "THB", "TJS",
  "TMT", "TND", "TOP", "TRY", "TTD", "TWD", "TZS", "UAH", "UGX", "USD", "UYU", "UZS", "VEF", "VES",
  "VND", "VUV", "WST", "XAF", "XAG", "XAU", "XCD", "XDR", "XOF", "XPD", "XPF", "XPT", "YER", "ZAR",
  "ZMW", "ZWL"
];
//Seznam jazyků, ten první bude vždy brán jako výchozí.
const langs = ["en","cz"];
//Texty a překlady na webu, v [0] je jazyk "en", v [1] je jazyk "cz"
const textTransl = {
  "zem": ["Country:", "Země:"],
  "men": ["Currency:", "Měna:"],
  "kurz_prode": ["We buy for", "Koupíme za:"],
  "kurz_koup": ["We sell for:", "Prodáme za:"],
  "aktualni_mena": ["Actual Currency: ", "Aktuální měna: "],
  "desetinne_carky": ["decimal points", "desetinných čárek"]
};